<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RFBaseIRepositories\RFBaseIRepositories.csproj" />
    <ProjectReference Include="..\RFBaseIServices\RFBaseIServices.csproj" />
    <ProjectReference Include="..\RFUserGroupsEntities\RFUserGroupsEntities.csproj" />
  </ItemGroup>

</Project>
