<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RFBaseServices\RFBaseServices.csproj" />
    <ProjectReference Include="..\RFPermissionsIServices\RFPermissionsIServices.csproj" />
    <ProjectReference Include="..\RFRBACEntities\RFRBACEntities.csproj" />
    <ProjectReference Include="..\RFRBACIRepositories\RFRBACIRepositories.csproj" />
    <ProjectReference Include="..\RFRBACIServices\RFRBACIServices.csproj" />
  </ItemGroup>

</Project>
