<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RFRegisterService\RFRegisterService.csproj" />
    <ProjectReference Include="..\RFEntities\RFEntities.csproj" />
    <ProjectReference Include="..\RFIRepositories\RFIRepositories.csproj" />
    <ProjectReference Include="..\RFIServices\RFIServices.csproj" />
    <ProjectReference Include="..\RFL10n\RFL10n.csproj" />
    <ProjectReference Include="..\RFIRepositories\RFIRepositories.csproj" />
  </ItemGroup>

</Project>
