<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\loat-facade\rf-nugets\RFEntities\RFEntities.csproj" />
    <ProjectReference Include="..\RFBase\RFBase.csproj" />
  </ItemGroup>

</Project>
