<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RFAuthEntities\RFAuthEntities.csproj" />
    <ProjectReference Include="..\RFAuthIRepositories\RFAuthIRepositories.csproj" />
    <ProjectReference Include="..\RFAuthIServices\RFAuthIServices.csproj" />
    <ProjectReference Include="..\RFBaseServices\RFBaseServices.csproj" />
    <ProjectReference Include="..\RFPermissionsEntities\RFPermissionsEntities.csproj" />
    <ProjectReference Include="..\RFRBACEntities\RFRBACEntities.csproj" />
    <ProjectReference Include="..\RFRGOBACEntities\RFRGOBACEntities.csproj" />
  </ItemGroup>

</Project>
